Fix issue 244
Codeminer42/Punchclock pull request #260
Opened 2022-10-08 02:24 UTC by geeksilva97

2022-10-10 14:45 UTC, adbatista commented
please add a better PR title

2022-11-01 22:32 UTC, adbatista requested changes

2022-11-03 14:20 UTC, FabioSaito commented on spec/controllers/my_contributions_controller_spec.rb
> +                                  .and have_content(Contribution.human_attribute_name("pr_state/#{contribution_list[0].pr_state}"))
```suggestion
                                  .and have_content(contribution_list[0].pr_state_text"))
```
The same approach can be applied here

2022-11-14 14:30 UTC, abarbosa-godaddy commented
getting back to work on that, guys.

2022-11-14 14:36 UTC, HeitorMC commented
> getting back to work on that, guys.

Don't worry. I'll work on that from now :+1: :handshake:

2022-11-14 21:14 UTC, HeitorMC commented on app/controllers/my_contributions_controller.rb
> +class MyContributionsController < ApplicationController
I agree. However, if we change this to `contributions_controller`, we need to move the existing `spec/controllers/contributions_controller.spec.rb` to a different folder. What do you recommend? @adbatista

2022-11-16 14:10 UTC, adbatista commented on config/locales/pt-BR/views.yml
> +  my_contributions:
rename this key to match the controller name pleas

2022-11-16 14:10 UTC, HeitorMC commented on app/controllers/my_contributions_controller.rb
> +class MyContributionsController < ApplicationController
Fixed

2022-11-16 14:10 UTC, HeitorMC commented on app/controllers/my_contributions_controller.rb
> +    @user_contributions = current_user.contributions.where(state: :approved).order(created_at: :desc)
Fixed

2022-11-16 14:10 UTC, HeitorMC commented on app/views/my_contributions/index.html.erb
> +                  <td><%= contribution.created_at.strftime('%d/%m/%Y') %></td>
Fixed

2022-11-16 14:16 UTC, HeitorMC commented on app/views/my_contributions/index.html.erb
> +                <th><%= t 'my_contributions.pr_link' %></th>
Sure! Already made the changes

2022-11-16 14:19 UTC, HeitorMC commented on app/views/my_contributions/index.html.erb
> +              <% end %>
Not really. if this `if-else` statement is true, the following `each` won't load anything because `user_contributions` is empty :handshake:

2022-11-16 14:20 UTC, HeitorMC commented on app/views/my_contributions/index.html.erb
> +                  <td><%= contribution.pr_state.nil? ? '-' : Contribution.human_attribute_name("pr_state/#{contribution.pr_state}") %></td>
Cool, I did not know it! Already made the changes, ty! :handshake:

2022-11-16 14:20 UTC, HeitorMC commented on spec/controllers/my_contributions_controller_spec.rb
> +                                  .and have_content(Contribution.human_attribute_name("pr_state/#{contribution_list[0].pr_state}"))
Fixed

2022-11-16 15:34 UTC, merged