Adds user's current allocation in navbar
Codeminer42/Punchclock pull request #27
Opened 2021-09-16 17:21 UTC by LucasHFS

Added the current allocation below the name of the user in the navbar.

Closes #5

2021-09-17 11:41 UTC, wenderjean commented on app/controllers/application_controller.rb
> +  def current_user
Would we have issues moving this method under the `protected` session?
Can we create a spec to ensure the object returned will be always a decorated user?

2021-09-17 13:49 UTC, adbatista requested changes
missing specs

2021-09-20 13:44 UTC, wenderjean commented on spec/decorators/user_decorator_spec.rb
> +    context 'when the current user is not an admin and user is allocated and' do
There is an ending `and` here :nail_care:

2021-09-20 13:58 UTC, wenderjean approved these changes
LGTM

2021-09-20 13:59 UTC, adbatista approved these changes

2021-09-20 13:59 UTC, merged