Removes punch button and adds dropdown options on menu
Codeminer42/Punchclock pull request #41
Opened 2021-09-26 15:29 UTC by LucasHFS

solves #15.

![cm42](https://user-images.githubusercontent.com/45002716/134814227-2e0165e0-cbcc-4e09-97cb-8ede69d25262.png)

2021-09-27 12:39 UTC, wenderjean requested changes

2021-09-27 12:39 UTC, wenderjean commented on app/views/refills/_navigation.html.erb
> +    <nav class='navbar navbar-expand navbar-dark static-top'>
For the sake of our sanity, I believe we should continue with double quotes.

2021-09-27 13:02 UTC, wenderjean commented on app/views/refills/_navigation.html.erb
> +            <%= link_to t('activerecord.modelsevaluation.other'), evaluations_path %>
Is this change intentional?

2021-09-27 13:02 UTC, wenderjean commented on config/locales/pt-BR/pt-BR.yml
> +      punches: 'Punches'
Can we continue using double quotes here also to keep the file consistent?

2021-10-01 11:09 UTC, wenderjean commented on config/locales/pt-BR/pt-BR.yml
> +      single_punch: "Single Punch"
Considerando que estamos tratando do arquivo `pt-BR.yml`, vai ser mais interessante se colocarmos algo como:
```
punches: "Punches"
single_punch: "Cadastrar Punch"
multiple_punches: "Múltiplos Punches"
```

Esse versão atual leve para o `en.yml` por favor.

2021-10-01 20:01 UTC, adbatista commented
please rebase your code to sync with the new master chantes

2021-10-04 11:24 UTC, wenderjean approved these changes

2021-10-04 11:24 UTC, merged