Feat: show page for repository in new admin
Codeminer42/Punchclock pull request #609
Opened 2023-11-10 18:30 UTC by EduardoSCosta

Resolve #608 

- [x] Create repository show page;
- [x] Create show repository request specs.

#### Repository show page in new admin
![Screenshot from 2023-11-10 15-09-11](https://github.com/Codeminer42/Punchclock/assets/30778707/07cf8250-e31e-4ed3-b1f9-15bbb211e6ff)

2023-11-13 11:59 UTC, nehamamandelbaum requested changes

2023-11-13 11:59 UTC, nehamamandelbaum commented on app/views/new_admin/repositories/show.html.erb
> +  <div id="project_actions" class="flex items-center justify-end">
```suggestion
  <div id="repository_actions" class="flex items-center justify-end">
```

2023-11-13 13:02 UTC, nehamamandelbaum approved these changes

2023-12-05 22:56 UTC, Lucas-Boeira approved these changes

2023-12-07 19:18 UTC, merged